#!/usr/bin/env bash

set -euo pipefail # STRICT MODE
IFS=$'\n\t'       # http://redsymbol.net/articles/unofficial-bash-strict-mode/

"$SBT" transferPublishAndTagResources

scripts/publishAndTag 'slamdata/tectonic'

bumpInDownstream() { echo $1 > tectonic-version; }
export -f bumpInDownstream

scripts/bumpDependentProject slamdata quasar bumpInDownstream
scripts/bumpDependentProject slamdata qdata bumpInDownstream
scripts/bumpDependentProject slamdata mimir bumpInDownstream
scripts/bumpDependentProject slamdata scion bumpInDownstream
scripts/bumpDependentProject slamdata quasar-datasource-url bumpInDownstream
